### ISSUE TITLE
We lost an external Image link

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#178]
The [Catalog Homepage](https://data.ioos.us/) used to have a glider image that looks like it was sourced from the https://ioos.noaa.gov site.  That was recently updated and URLs changed.  

Can we find the new link and replace the dead one?  Former location: 

https://ioos.noaa.gov/wp-content/uploads/2016/04/deployCTD2.jpg

**Comment by mwengren** [comment]
FYI, looks like this is the new URL for that image:

https://cdn.ioos.noaa.gov/media/2015/10/deployCTD2_crop.jpg

**Comment by mwengren** [comment]
This should do it: https://cdn.ioos.noaa.gov/media/2017/12/deployCTD2-300x225.jpg

**Comment by benjwadams** [comment]
Part of #182, this should be fixed when that PR is merged.

**Comment by mwengren** [comment]
@benjwadams Can we merge this one separate of #182 and resolve that one later?  I would need an update on the various feedback efforts you all worked on a few months ago to know where to go with the feedback button situation in Catalog (as described in #182).

**Comment by mwengren** [comment]
@benjwadams The missing homepage image is still an issue on both the live and development versions of the Catalog, so it appears #182 didn't fix this anyway.  Can we make sure that the original image is back when we deploy the 2.8 upgrade (this week, if we're still on track for that). 

Not sure what to say on the feedback topic, we can hold off on that for this release, since #182 didn't seem to add the left-side feedback button anyway.

**Comment by benjwadams** [comment]
Image is reappearing due to use of the new ckanext-ioos-theme.
